variables:
  SONARQUBE_IMAGE: sonarqube:latest
  DATABASE_IMAGE: mcr.microsoft.com/mssql/server:latest
  BACKEND_IMAGE: autoindetify-backend:latest
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - docker info

#sonarqube_analysis:
#  stage: sonarqube
#  script:
#    - ./gradlew jacocoTestReport sonarqube
#  only:
#    - main

stages:
  - build
  - test
#  - sonarqube
  - deploy

build:
  stage: build
  script:
    - ./gradlew clean assemble
    - docker build -t $BACKEND_IMAGE .

test:
  stage: test
  script:
    - ./gradlew test

deploy_backend:
  stage: deploy
  script:
    - docker stop autoindetify-be || $true
    - docker rm autoindetify-be || $true
    - docker run -d -p 8090:8080 --net=docker_demo_network_staging --env spring_profiles_active=staging --name autoidentify-be $BACKEND_IMAGE
deploy_database:
  stage: deploy
  script:
    - docker stop autoidentifydb || $true
    - docker rm autoidentifydb || $true
    - docker pull $DATABASE_IMAGE
    - docker run -d -e ACCEPT_EULA=Y -e SA_PASSWORD=1234 -p 1433:1433 --name autoidentifydb $DATABASE_IMAGE