variables:
  SONARQUBE_IMAGE: sonarqube:latest
  DATABASE_IMAGE: mcr.microsoft.com/mssql/server:latest
  BACKEND_IMAGE: autoindetify-backend:latest
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - docker info

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew clean assemble
    - docker build -t $env:BACKEND_IMAGE .

test:
  stage: test
  script:
    - ./gradlew test

deploy_backend:
  stage: deploy
  script:
    - |
      try {
        docker stop autoidentify-be
      } catch {
        Write-Host "Failed to stop the container, continuing..."
      }
    - |
      try {
        docker rm autoidentify-be
      } catch {
        Write-Host "Failed to remove the container, continuing..."
      }
    - docker run -d -p 8090:8080 --net=docker_demo_network_staging --env spring_profiles_active=staging --name autoindetify-be $env:BACKEND_IMAGE


deploy_database:
  stage: deploy
  script:
    - |
      try {
        docker stop autoidentifydb
      } catch {
        Write-Host "Failed to stop the container, continuing..."
      }
    - |
      try {
        docker rm autoidentifydb
      } catch {
        Write-Host "Failed to remove the container, continuing..."
      }
    - docker pull $env:DATABASE_IMAGE
    - docker run -d -e ACCEPT_EULA=Y -e SA_PASSWORD=1234 -p 1433:1433 --name autoidentifydb $env:DATABASE_IMAGE
